### ISSUE TITLE
Install on Julia 1.0

### ISSUE THREAD

**Issue by jcreinhold** [JuliaIO/NIfTI.jl#18]
I tried to install the package on Julia 1.0 but it failed with a litany of errors. I am new to Julia, so perhaps I am just doing something incorrectly.

My first attempt was to just do:

```julia
Pkg.add("NIfTI")
ERROR: The following package names could not be resolved:
 * NIfTI (not found in project, manifest or registry)
Please specify by known `name=uuid`.
```

Then, after looking at the .travis.yml, I tried:

```julia
julia> Pkg.clone("https://github.com/JuliaIO/NIfTI.jl")
┌ Warning: Pkg.clone is only kept for legacy CI script reasons, please use `add`
└ @ Pkg.API /Users/vagrant/worker/juliapro-release-osx1011-0_6/build/tmp_julia/Julia-1.0.app/Contents/Resources/julia/share/julia/stdlib/v1.0/Pkg/src/API.jl:467
   Cloning git-repo `https://github.com/JuliaIO/NIfTI.jl`
  Updating git-repo `https://github.com/JuliaIO/NIfTI.jl`
[ Info: Assigning UUID 6c109ca0-f035-5759-99cf-3962dcd1658a to NIfTI
 Resolving package versions...
 Installed GZip ───────── v0.5.0
 Installed MappedArrays ─ v0.2.1
ERROR: The following package names could not be resolved:
 * julia (not found in project, manifest or registry)
Please specify by known `name=uuid`.
```

Should I try something else or do I just need to roll-back to v0.6?

**Comment by Tokazama** [comment]
I'm definitely not the expert here (also new to Julia) but my current [pull request](https://github.com/JuliaIO/NIfTI.jl/pull/17) passes all tests in 1.0 and has been working pretty well. I'm currently using it in dev mode though. This means my git clone on file is the default loaded when `using NIfTI`.
```
using Pkg
Pkg.develop(PackageSpec(url="somepath/NIfTI.jl")
```
If you're using a lot of packages with 0.6 compatibility but not 1.0 you may want to use 0.7. It's like a bridge version that gives warnings for deprecations from 0.6 instead of just errors. This is especially helpful if you're trying to help make a package 1.0 compatible.

**Comment by Tokazama** [comment]
Should work now

**Comment by jcreinhold** [comment]
@Tokazama I tried to re-install and am receiving the following error:

```julia
julia> Pkg.add(PackageSpec(url="https://github.com/Tokazama/NIfTI.jl"))
  Updating git-repo `https://github.com/Tokazama/NIfTI.jl`
[ Info: Assigning UUID 6c109ca0-f035-5759-99cf-3962dcd1658a to NIfTI
 Resolving package versions...
 Installed OrderedCollections ─ v1.0.1
 Installed GZip ─────────────── v0.5.0
 Installed Compat ───────────── v1.1.0
 Installed IterTools ────────── v1.0.0
ERROR: The following package names could not be resolved:
 * julia (not found in project, manifest or registry)
Please specify by known `name=uuid`.
```

For what its worth, if I install in the pkg environment I also receive the same message:

```julia
(JuliaPro_v1.0.1.1) pkg> add "https://github.com/Tokazama/NIfTI.jl"
  Updating git-repo `https://github.com/Tokazama/NIfTI.jl`
[ Info: Assigning UUID 6c109ca0-f035-5759-99cf-3962dcd1658a to NIfTI
 Resolving package versions...
 Installed GZip ─────────────── v0.5.0
 Installed Compat ───────────── v1.1.0
 Installed OrderedCollections ─ v1.0.1
 Installed IterTools ────────── v1.0.0
ERROR: The following package names could not be resolved:
 * julia (not found in project, manifest or registry)
Please specify by known `name=uuid`.
```

Any thoughts?

**Comment by jcreinhold** [comment]
Looking at the documentation for v1.0 ([link](https://docs.julialang.org/en/v1.0/stdlib/Pkg/#Creating-your-own-packages-1)), it looks like the REQUIRE file has been completely replaced and dependencies are handled differently. @Tokazama have you modified your environment to handle installation in a different way, by chance?

Also, just wanted to say thank you very much for the help!

**Comment by Tokazama** [comment]
Did you remove the previous version of NIfTI.jl before re-installing

**Comment by jcreinhold** [comment]
I used gc to remove old installations and tried again and failed. To make sure I deleted all the cache files, I deleted the .julia directory in ~ and all of the support files as well as the JuliaPro application and re-installed JuliaPro. I receive a similar error:

```julia
(JuliaPro_v1.0.1.1) pkg> add https://github.com/Tokazama/NIfTI.jl
  Updating registry at `/Applications/JuliaPro-1.0.1.1.app/Contents/Resources/pkgs-1.0.1.1/registries/JuliaPro`
  Updating git-repo `https://pkg.juliacomputing.com/registry/JuliaPro`
[ Info: Please Authenticate..
   Cloning git-repo `https://github.com/Tokazama/NIfTI.jl`
  Updating git-repo `https://github.com/Tokazama/NIfTI.jl`
[ Info: Assigning UUID 6c109ca0-f035-5759-99cf-3962dcd1658a to NIfTI
 Resolving package versions...
 Installed GZip ─ v0.5.0
ERROR: The following package names could not be resolved:
 * julia (not found in project, manifest or registry)
Please specify by known `name=uuid`.
```

**Comment by Tokazama** [comment]
I've been able to delete and redownload it on my computer but I don't have access to another computer at the moment for further testing. One thing that I find odd is that your registry is under the `/Applications/JuliaPro...`. Where it is usually under `~/.julia/registries/`. I don't know if that has anything to do with it. Usually you would only need to do something like `rm(joinpath(homedir(), ".julia", "registries"); recursive=true)` in order to fix this problem (from what i've read and my personal experiences). 

A temporary solution that would probably work is  `Pkg.develop(PackageSpec(url="https://github.com/Tokazama/NIfTI.jl")` (as opposed to `Pkg.add`). 

Side note: I believe `REQUIRE` is still necessary as the packaging system transitions.

**Comment by jcreinhold** [comment]
Thanks for the update @Tokazama and the note about the `REQUIRE` file. 

So I was able to install the package (!). I uninstalled JuliaPro and installed the vanilla version and it worked immediately. I'm going to keep this issue open since your PR request hasn't been merged. Thank you for supporting the package and your help @Tokazama

**Comment by jcreinhold** [comment]
@Tokazama's PR seems to be merged so I'm closing this issue.
